//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BaiLam
    {
        public int IdNguoiDung { get; set; }
        public int IdBaiTap { get; set; }

        [Display(Name = "Bài Làm")]
        public Nullable<int> IdFileBaiLam { get; set; }

        [Display(Name = "Nhận Xét")]
        public string NhanXet { get; set; }

        [Display(Name = "Điểm")]
        [Range(0, 10, ErrorMessage = "Please enter a number between 0 and 10.")]
        public Nullable<double> Diem { get; set; }
        public bool NopMuon { get; set; }

        [Display(Name = "Ngày Nộp")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime NgayNop { get; set; }
    
        public virtual BaiTap BaiTap { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
