//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BaiTap
    {
        public BaiTap()
        {
            this.BaiLams = new HashSet<BaiLam>();
            ChoPhepGiaHan = false;
            DanhDauNopMuon = false;
            SoNgayGiaHan = 0;
            IsKetThuc = false;
        }
    
        public int IdBaiTap { get; set; }

        [Display(Name = "Tên Bài Tập")]
        public string TenBaiTap { get; set; }

        public Nullable<int> IdLopMonHoc { get; set; }

        [Display(Name = "Mô Tả Bài Tập")]
        [DataType(DataType.MultilineText)]
        public string MoTaBaiTap { get; set; }

        [Display(Name = "Đề Bài Tập")]
        public Nullable<int> IdDeBaiTap { get; set; }

        [Display(Name = "Định Dạng File Bài Làm")]
        public string DinhDangFileBaiLam { get; set; }

        [Display(Name = "Dung Lượng File Bài Làm")]
        public string DungLuongFileBaiLam { get; set; }

        [Display(Name = "Cho Phép Xem Bài")]
        public bool ChoPhepXemBai { get; set; }

        [Display(Name = "Bắt Đầu")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }


        [Display(Name = "Nộp Bài")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ThoiGianNopBai { get; set; }

        [Display(Name = "Cho Phép Gia Hạn")]
        public bool ChoPhepGiaHan { get; set; }

        [Display(Name = "Số Ngày Gia Hạn")]
        public int SoNgayGiaHan { get; set; }

        [Display(Name = "Đánh Dấu Nộp Muộn")]
        public bool DanhDauNopMuon { get; set; }

        [Display(Name = "Kết Thúc")]
        public bool IsKetThuc { get; set; }
    
        public virtual ICollection<BaiLam> BaiLams { get; set; }
        public virtual LopMonHoc LopMonHoc { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
