//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BuoiHoc
    {
        public BuoiHoc()
        {
            this.DiemDanhs = new HashSet<DiemDanh>();
        }

        [Display(Name = "Id Buổi Học")]
        public int IdBuoiHoc { get; set; }

        [Display(Name = "Lớp Môn Học")]
        public Nullable<int> IdLopMonHoc { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Ngày Học")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime NgayHoc { get; set; }
    
        public virtual LopMonHoc LopMonHoc { get; set; }
        public virtual ICollection<DiemDanh> DiemDanhs { get; set; }
    }
}
