//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuDeTraoDoi
    {
        public ChuDeTraoDoi()
        {
            this.TraoDois = new HashSet<TraoDoi>();
        }
    
        public int IdChuDe { get; set; }
        public string TenChuDe { get; set; }
        public Nullable<int> IdLopMonHoc { get; set; }
    
        public virtual LopMonHoc LopMonHoc { get; set; }
        public virtual ICollection<TraoDoi> TraoDois { get; set; }
    }
}
