//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DiemDanh
    {
        public int IdBuoiHoc { get; set; }
        public int IdNguoiDung { get; set; }

        [Display(Name = "Tình Trạng Đi Học")]
        public Nullable<int> IdTinhTrangDiHoc { get; set; }

        [Display(Name = "Nhận Xét")]
        public string NhanXet { get; set; }

        public virtual BuoiHoc BuoiHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TinhTrangDiHoc TinhTrangDiHoc { get; set; }
    }
}
