//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViQuanLy
    {
        public DonViQuanLy()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public int IdDonViQuanLy { get; set; }
        public string TenDonViQuanLy { get; set; }
    
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
    }
}
