//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeDaoTao
    {
        public HeDaoTao()
        {
            this.MonHoc_HeDaoTao = new HashSet<MonHoc_HeDaoTao>();
        }
    
        public int IdHeDaoTao { get; set; }
        public string TenHeDaoTao { get; set; }
    
        public virtual ICollection<MonHoc_HeDaoTao> MonHoc_HeDaoTao { get; set; }
    }
}
