//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiTaiLieu
    {
        public LoaiTaiLieu()
        {
            this.TaiLieux = new HashSet<TaiLieu>();
        }
    
        public int IdLoaiTaiLieu { get; set; }
        public string TenLoaiTaiLieu { get; set; }
    
        public virtual ICollection<TaiLieu> TaiLieux { get; set; }
    }
}
