//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class LopMonHoc
    {
        public LopMonHoc()
        {
            this.BaiTaps = new HashSet<BaiTap>();
            this.BuoiHocs = new HashSet<BuoiHoc>();
            this.ChuDeTraoDois = new HashSet<ChuDeTraoDoi>();
            this.DanhSaches = new HashSet<DanhSach>();
            this.TaiLieu_LopMonHoc = new HashSet<TaiLieu_LopMonHoc>();
            this.ThongBaos = new HashSet<ThongBao>();
            this.TinhTrangDiHoc_BuoiNghi = new HashSet<TinhTrangDiHoc_BuoiNghi>();
            this.YeuCauThamGias = new HashSet<YeuCauThamGia>();
        }

        [Key]
        public int IdLopMonHoc { get; set; }

        [Display(Name = "Mã Lớp")]
        public int MaLopMonHoc { get; set; }

        [Display(Name = "Số Tiết")]
        public int SoTiet { get; set; }

        public Nullable<int> IdMonHocHeDaoTao { get; set; }

        [Display(Name = "Tên Lớp")]
        public string TenLopMonHoc { get; set; }

        [Display(Name = "Số Buổi")]
        public int SoBuoiDiemDanh { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Bắt Đầu")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ThoiGianBatDau { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Kết Thúc")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ThoiGianKetThuc { get; set; }

        [Display(Name = "Công Khai")]
        public bool CongKhai { get; set; }

        [Display(Name = "Người Tạo")]
        public int IdNguoiDung { get; set; }

        [Display(Name = "Đề Cương Bài Giảng")]
        public Nullable<int> IdDeCuongBaiGiang { get; set; }
    
        public string TenLopFull
        {
            get
            {
                return MonHoc_HeDaoTao.TenMonHocHeDaoTao + " - " + SoTiet + " tiết - " + NguoiDung.HoTen;
            }
        }

        public virtual ICollection<BaiTap> BaiTaps { get; set; }
        public virtual ICollection<BuoiHoc> BuoiHocs { get; set; }
        public virtual ICollection<ChuDeTraoDoi> ChuDeTraoDois { get; set; }
        public virtual ICollection<DanhSach> DanhSaches { get; set; }
        public virtual MonHoc_HeDaoTao MonHoc_HeDaoTao { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
        public virtual ICollection<TaiLieu_LopMonHoc> TaiLieu_LopMonHoc { get; set; }
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
        public virtual ICollection<TinhTrangDiHoc_BuoiNghi> TinhTrangDiHoc_BuoiNghi { get; set; }
        public virtual ICollection<YeuCauThamGia> YeuCauThamGias { get; set; }
    }
}
