//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc_HeDaoTao
    {
        public MonHoc_HeDaoTao()
        {
            this.LopMonHocs = new HashSet<LopMonHoc>();
        }
    
        public int IdMonHocHeDaoTao { get; set; }
        public Nullable<int> IdMonHoc { get; set; }
        public Nullable<int> IdHeDaoTao { get; set; }
        public string TenMonHocHeDaoTao { get; set; }
        public Nullable<int> IdDeCuongMonHoc { get; set; }
        public Nullable<int> IdDeCuongChiTiet { get; set; }
    
        public virtual HeDaoTao HeDaoTao { get; set; }
        public virtual ICollection<LopMonHoc> LopMonHocs { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
