//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.BaiLams = new HashSet<BaiLam>();
            this.DanhSaches = new HashSet<DanhSach>();
            this.DiemDanhs = new HashSet<DiemDanh>();
            this.LopMonHocs = new HashSet<LopMonHoc>();
            this.TaiLieux = new HashSet<TaiLieu>();
            this.ThongBaos = new HashSet<ThongBao>();
            this.TraoDois = new HashSet<TraoDoi>();
            this.YeuCauThamGias = new HashSet<YeuCauThamGia>();
        }
    
        public int IdNguoiDung { get; set; }

        [Display(Name = "Ảnh")]
        public string DuongDanAnh { get; set; }

        [Display(Name = "Họ Tên")]
        public string HoTen { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Ngày Sinh")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgaySinh { get; set; }

        [Display(Name = "Quê Quán")]
        public string QueQuan { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Ngày Tạo Tài Khoản")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayTaoTaiKhoan { get; set; }

        [Display(Name = "Đơn Vị Quản Lý")]
        public Nullable<int> IdDonViQuanLy { get; set; }

        [Display(Name = "Mã")]
        public string UserName { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Loại Người Dùng")]
        public Nullable<int> IdLoaiNguoiDung { get; set; }

        [Display(Name = "Học Hàm")]
        public string HocHam { get; set; }

        [Display(Name = "Học Vị")]
        public string HocVi { get; set; }
    
        public virtual ICollection<BaiLam> BaiLams { get; set; }
        public virtual ICollection<DanhSach> DanhSaches { get; set; }
        public virtual ICollection<DiemDanh> DiemDanhs { get; set; }
        public virtual DonViQuanLy DonViQuanLy { get; set; }
        public virtual LoaiNguoiDung LoaiNguoiDung { get; set; }
        public virtual ICollection<LopMonHoc> LopMonHocs { get; set; }
        public virtual ICollection<TaiLieu> TaiLieux { get; set; }
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
        public virtual ICollection<TraoDoi> TraoDois { get; set; }
        public virtual ICollection<YeuCauThamGia> YeuCauThamGias { get; set; }
    }
}
