//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyLopTinChiEntities : DbContext
    {
        public QuanLyLopTinChiEntities()
            : base("name=QuanLyLopTinChiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaiLam> BaiLams { get; set; }
        public DbSet<BaiTap> BaiTaps { get; set; }
        public DbSet<BuoiHoc> BuoiHocs { get; set; }
        public DbSet<ChuDeTraoDoi> ChuDeTraoDois { get; set; }
        public DbSet<DanhSach> DanhSaches { get; set; }
        public DbSet<DiemDanh> DiemDanhs { get; set; }
        public DbSet<DonViQuanLy> DonViQuanLies { get; set; }
        public DbSet<HeDaoTao> HeDaoTaos { get; set; }
        public DbSet<LoaiNguoiDung> LoaiNguoiDungs { get; set; }
        public DbSet<LoaiTaiLieu> LoaiTaiLieux { get; set; }
        public DbSet<LopMonHoc> LopMonHocs { get; set; }
        public DbSet<MonHoc> MonHocs { get; set; }
        public DbSet<MonHoc_HeDaoTao> MonHoc_HeDaoTao { get; set; }
        public DbSet<NguoiDung> NguoiDungs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TaiLieu> TaiLieux { get; set; }
        public DbSet<TaiLieu_LopMonHoc> TaiLieu_LopMonHoc { get; set; }
        public DbSet<ThongBao> ThongBaos { get; set; }
        public DbSet<TinhTrangDiHoc> TinhTrangDiHocs { get; set; }
        public DbSet<TinhTrangDiHoc_BuoiNghi> TinhTrangDiHoc_BuoiNghi { get; set; }
        public DbSet<TraoDoi> TraoDois { get; set; }
        public DbSet<YeuCauThamGia> YeuCauThamGias { get; set; }
    }
}
