//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu_LopMonHoc
    {
        public int IdTaiLieu { get; set; }
        public int IdLopMonHoc { get; set; }
        public string GhiChu { get; set; }
    
        public virtual LopMonHoc LopMonHoc { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
