//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int IdThongBao { get; set; }
        public Nullable<int> IdNguoiDung { get; set; }
        public Nullable<int> IdLopMonHoc { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> IsDaDoc { get; set; }
    
        public virtual LopMonHoc LopMonHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
