//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTrangDiHoc
    {
        public TinhTrangDiHoc()
        {
            this.DiemDanhs = new HashSet<DiemDanh>();
            this.TinhTrangDiHoc_BuoiNghi = new HashSet<TinhTrangDiHoc_BuoiNghi>();
        }
    
        public int IdTinhTrangDiHoc { get; set; }
        public string NoiDung { get; set; }
        public string KyHieu { get; set; }
    
        public virtual ICollection<DiemDanh> DiemDanhs { get; set; }
        public virtual ICollection<TinhTrangDiHoc_BuoiNghi> TinhTrangDiHoc_BuoiNghi { get; set; }
    }
}
