//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTrangDiHoc_BuoiNghi
    {
        public int IdTinhTrangDiHoc { get; set; }
        public int IdLopMonHoc { get; set; }
        public Nullable<double> TuongDuongBuoiNghi { get; set; }
    
        public virtual LopMonHoc LopMonHoc { get; set; }
        public virtual TinhTrangDiHoc TinhTrangDiHoc { get; set; }
    }
}
