//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLopTinChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraoDoi
    {
        public int IdTraoDoi { get; set; }
        public Nullable<int> IdNguoiDung { get; set; }
        public Nullable<int> IdChuDe { get; set; }
        public string NoiDungTraoDoi { get; set; }
    
        public virtual ChuDeTraoDoi ChuDeTraoDoi { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
